name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v6
        with:
          node-version: 25

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Build/release Electron app
        shell: bash
        run: |
          releaseArgs=""
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            releaseArgs="--publish always"
          fi
          yarn run electron-builder $releaseArgs
        env:
          GH_TOKEN: ${{ secrets.github_token }}
